#!/usr/bin/env bash
# Script to configure a new Ubuntu machine.
apt-get update;
apt-get -y install nginx;
service nginx start;
echo "Holberton School" | tee /usr/share/nginx/html/index.html;
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/custom_404.html;
TO_REPLACE="^server {$";
REPLACE_WITH="server {\n\tlocation \/redirect_me\/ {\n\t\trewrite ^\/redirect_me\/$ http:\/\/www.dragonvipercobra.com permanent;\n\t}\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}\n";
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/.old_default;
sed -i "s/$TO_REPLACE/$REPLACE_WITH/" /etc/nginx/sites-available/default;
service nginx reload;
service nginx restart;
