#!/usr/bin/env bash
# Script to generate a MySQL dump and create a compressed archive out of it
DATE=$(date +%d-%m-%Y)
PASSWORD=$1
mysqldump -uroot -p"$PASSWORD" --all-databases > backup.sql
tar -czvf "$DATE.tar.gz" backup.sql
