#!/usr/bin/env bash
#Init script for manage_my_process

PIDFILE=/var/run/my_process.pid
MMP=manage_my_process
#PIDS=$(pgrep MMP)

case "$1" in
     start)
	./$MMP &
	echo "$MMP started"
	;;
     stop)
	kill "$(cat $PIDFILE)"
	rm -f $PIDFILE
	echo "$MMP stopped"
	;;
     restart)
	kill "$(cat $PIDFILE)"
	rm -f $PIDFILE
	./$MMP &
	echo "$MMP restarted"
	;;
     *)
	echo "Usage: $MMP {start|restart|stop}"
	;;
esac
