#!/usr/bin/env bash
# Bash script that displays a string indefinitely

FILE=/var/run/holbertonscript.pid
echo $BASHPID > $FILE

trap 'echo Y U no love me?!' SIGINT
trap 'echo I hate the kill command; rm -f $FILE; exit' SIGTERM
trap 'rm -f $FILE; exit' SIGQUIT

while :
do
    echo "To infinity and beyond"
done
