#!/usr/bin/env bash
#Script that displays numbers from 1 to 100 in the following format:
# multiple of 3: displays as Fizz
# multiple of 5: displays as Buzz
# multiple of 3 and 5: displays as FizzBuzz
# all other numbers: displays the number
for ((i=1; i <= 100; i++));
do
    if [ $((i % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i % 5)) -eq 0 ]
    then
	echo "Buzz"
    elif [ $((i % 3)) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
