#!/usr/bin/env bash
# Script that prints the following lines based on iterations:
# 4th: "bad luck from China"
# 9th: "bad luck from Japan"
# 17th: "bad luck from Italy"
# all others: "Holberton School"
COUNTER=1
while [ $COUNTER -le 20 ]; do
    case $COUNTER in
	4)
	    echo "$COUNTER"
	    echo "bad luck from China";;
	9)
	    echo "$COUNTER"
	    echo "bad luck from Japan";;
	17)
	    echo "$COUNTER"
	    echo "bad luck from Italy";;
	*)
	    echo "$COUNTER";;
    esac
    let COUNTER+=1
done
