#!/usr/bin/env bash
#Script to provide information about the holbertonschool file
#check if file exists

if [ -e "holbertonschool" ]
then
    echo "holbertonschool file exists"
    # check if file is empty
    if [ -s "holbertonschool" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    #check if file is a regular file
    if [ -f "holbertonschool" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
